### ISSUE TITLE
Make the 2K resistors a 603 and a .25 W

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#12]
replace the motor LED 2K resistors with a 1/4W 603.

**Comment by bgomberg** [comment]
I believe the issue here was that we are using a 0402 2k resistor, which
didn't come in a 1/4W version. So, we'll need to change it to a 0603 and
then change the BOM to use the correct 2k 1/W resistor.

**Comment by aithon** [comment]
There are 3 2K resistors.  Is this the one with the regulator?  Maybe this won't matter once we change the regulator.

**Comment by bgomberg** [comment]
No, this was for the 2 resistors on the motor LEDs. Those resistors could
have up to ~22V across them which would translate to 0.242W of power.

**Comment by cccitron** [comment]
A 603 for R38 won't fit next to LED7, between motorcontroller U4 and MOTOR0 currently. How close does the resistor need to be to the LED?

**Comment by bgomberg** [comment]
It can be anywhere, as long as routing the trace to it doesn't cause
additional issues.

**Comment by cccitron** [comment]
R37 and R38 are now 603's. I updated the AITHON_BOM_passive_sizing.xlsx file with them being 603's.

**Comment by cccitron** [comment]
Brian's recommendation: Change those two resistors from 2k to 3k.

**Comment by aithon** [comment]
Why 3K?  That will make the LED very dim at reasonable voltages.

**Comment by bgomberg** [comment]
2k is going to get very close (and could potentially exceed depending on
our new input voltage range) 1/4W for the resistor at high voltage. On the
current rev4 boards, the LED is still plenty bright at low voltages (7.4V
2S lithium-ion) across the range of the motor output voltages. Since the
input voltage is now 8V at minimum, I think people will likely use
somewhere around 12V (3S li-ion/lipo or 12V SLA). With a 3k, the brightness
at 12V input levels will be roughly the same, if not higher than current
board's brightness at 7.4V input.
