### ISSUE TITLE
add serial debugging mode to the bootloader

### ISSUE THREAD

**Issue by aithon** [aithon/aithon#22]
Add a way to enter a serial debugger or serial menu.  This should be built in to the bootloader.

**Comment by bgomberg** [comment]
I thought you meant just a serial console like Arduino has.

**Comment by aithon** [comment]
There should be a serial console in the IDE, but there should also be a serial mode in the bootloader.  If you enter serial mode in the bootloader, then you should be able to connect with the serial console in the IDE and see a nice menu.

**Comment by bgomberg** [comment]
I think there's a bunch of things we wanted in the bootloader. We should figure out all the other features we want; let's use this ticket for that for now?

Here's some ideas I had from our prior discussion and just things I've thought of:
1) Interactively access all parts of the board. This includes writing to the screen, reading analog pins, setting servo pins, setting motor speeds, etc. This requires having the entire aithon library as part of the bootloader.
2) Allow multiple programs to be within the FLASH at once, and be able to select which one we want to run by default through the serial console (and probably some other method to change it temporarily from the board itself).
3) Some sort of demo program? Maybe something that uses the gyro.
4) Load program off the sd card into FLASH.

Obviously this could make the bootloader rather large, but that's why we have 2MB of FLASH right? :)
